#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys, os

STUFFDIR = '/usr/share/python-whiteboard'

def main():
	global STUFFDIR
	if not os.path.isdir(STUFFDIR):
		print "Can't find " + STUFFDIR
		sys.exit(1)
	
	#apply our directories and test environment
	os.chdir(STUFFDIR)
	sys.path.insert(0, STUFFDIR)
	
	print "Using directory: " + STUFFDIR
	
	import pywhiteboard
	pywhiteboard.main()


if __name__ == '__main__': main()



